-- Table: public.url

-- DROP TABLE IF EXISTS public.url;

CREATE TABLE IF NOT EXISTS public.url
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    full_url character(2000) COLLATE pg_catalog."default" NOT NULL,
    short_code character(255) COLLATE pg_catalog."default" NOT NULL,
    date_created timestamp without time zone,
    CONSTRAINT url_pkey PRIMARY KEY (id),
    CONSTRAINT url_short_code_key UNIQUE (short_code)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.url
    OWNER to root;